### ISSUE TITLE
Update Build Your Own Queries page with new data for 2017-2018

### ISSUE THREAD

**Issue by feydan** [code4sac/openbudgetsac.org#13]
Now that we have the other visualizations updated with the 2017-2018 data, we should tackle the "Build your own queries" feature now.

The dataset is here: http://data.cityofsacramento.org/datasets/approved-budget-fy-2015-fy-2018

**Comment by joelrip** [comment]
Sorry I've been out of touch lately, but I have been working on this. I've got the basics done, but there are a few bugs to squash, I think due to the fact that some of the divisions in the departments changed names over the years, so the percent change from the previous year is breaking. Will update when I can.

**Comment by feydan** [comment]
Thanks @joelrip!

**Comment by joelrip** [comment]
This has been updated.
